package com.gagik.scriptrunner.domain.models

/**
 * Represents the various types of output that can be generated by a running script.
 * This is a sealed class, which means all possible output types are defined within this file.
 */
sealed class ScriptOutput {
    data class Line(val text: String) : ScriptOutput()
    data class Error(val message: String) : ScriptOutput()
    data class Exit(val code: Int) : ScriptOutput()
}